[package]
name = "pathsearch"
version = "0.4.0"
authors = ["Kesavan Yogeswaran <hikes@google.com>"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1"
rayon = "1"

[profile.release]
panic = "abort"
